### PR TITLE
Add a method to get download url of a File

### PR DESCRIPTION
**Pull request by jlejeune**
Just a little method to get download url of a File object.

### CODE REVIEW

**Comment by jlejeune** [comment]
What do you think @cenkalti ? I need this method to send downloadable links to another job in charge of downloading files and it's better to get these links directly from lib.

**Comment by cenkalti** [comment]
Hello @jlejeune.

Sorry for the delayed answer.

The link itself as returned from your proposed method won't work itself because there is no authentication token in it. You can use `get_stream_link` link method if you want to pass it to another workflow.

Let me know if you have further questions.

**Comment by jlejeune** [comment]
Agree with you, without token, the download link doesn't work, but the token has to be used to define an instance of Client class, so on customer side, and the lib doesn't have this information. The complete link has to be generated on customer side, concating BASE_URL + /files/<id>/download + token but it should be better if we can have BASE_URL + path from lib (if BASE_URL change in future for eample). But if you told me, I have to use stream_link, I will try.

**Comment by jlejeune** [comment]
Hi,
I answered you on pull request, dunno if you receive a notification because
pull request is closed.
--
Julien

**Comment by cenkalti** [comment]
Hi @jlejeune. I got the notification from GitHub.

What do you mean by "stream_link is not downloadable"?

**Comment by cenkalti** [comment]
Hi @jlejeune. I got the notification from GitHub.

What do you mean by "stream_link is not downloadable"?

**Comment by jlejeune** [comment]
Hi,

Indeed, It works with stream_link, I can download file with it, my fault.
Just little annoying thing is that downloaded file with it doesn't keep the name of the file but its id.

**Pull request closed without merging**
