### PR TITLE
Merged with your latest changes

### PR DESCRIPTION
**Pull request by datashaman**
Various changes for your PR

### CODE REVIEW

**Comment by cenkalti** [comment]
I have added a method for deleting multiple files and transfers: https://github.com/cenkalti/putio.py/commit/16b33e0f97d66c46b6edf2bb19e3a4c3d3c9b515

**Comment by cenkalti** [comment]
Uploaded new version to PyPI. I hope everything is okay on your side.

**Comment by datashaman** [comment]
Sweet! I'll test it out now.

**Comment by datashaman** [comment]
The only problem I can see is that neither _multi method turns the integer
IDs into strings, so it fails if you use the IDs from the transfer payload
(which are integers)

**Comment by datashaman** [comment]
I can work around it, but it would be nice to have that fix back:

    "transfer_ids": ','.join([ str(t.id) for t in transfer_ids ])

**Comment by datashaman** [comment]
Also, including 500 may cause unnecessary retries, but I'll let you know if
i experience problems.

**Comment by datashaman** [comment]
Whoot! Got my first release out, thanks for your help!

https://github.com/datashaman/putio-automator/releases/tag/0.1.0

**Comment by datashaman** [comment]
I notice you don't tag your releases. It is std practice on each release to
tag the master branch with the release number. It is quite useful to easily
go back to a specific release to see the differences, and allows users of
your library to select specific versions to use on github (if they don't
use PyPI eggs).

Have a look at this for a good branching and releasing strategy:

http://nvie.com/posts/a-successful-git-branching-model/
https://github.com/nvie/gitflow

**Comment by cenkalti** [comment]
Fixed the issue with ```_multi()``` methods and uploaded the new version to PyPI. Thanks for reporting this.

**Comment by datashaman** [comment]
​genius use of map. doh! :)​

**Pull request closed without merging**
